ELearning/ELearning/Controllers/EditorController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ELearning.DAL;
using ELearning.Models;

namespace ELearning.Controllers
{
    public class EditorController : Controller
    {
        private tblContentsContext db = new tblContentsContext();
      
        public ActionResult ContentManagement()
        {
            
            var Çontent = db.tblContent.Include(t => t.tblCourse);
            return View(Çontent.ToList());
        }

        // GET: tblContents/Create
        public ActionResult Create()
        {
           
            return View();
        }
        // GET: tblContents/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblContent tblContent = db.tblContent.Find(id);
            if (tblContent == null)
            {
                return HttpNotFound();
            }
            return View(tblContent);
        }
        // GET: tblContents/Create
        public ActionResult NewContent()
        {
            return View();
        }
        // POST: tblContents/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult NewContent([Bind(Include = "id,title,clevel,description,cid,date")] tblContent tblContent)
        {
            if (ModelState.IsValid)
            {
                db.tblContent.Add(tblContent);
                db.SaveChanges();
                return RedirectToAction("ContentManagment");
            }

            return View(tblContent);
        }


        // GET: tblContents/Edit/5
        public ActionResult Edite(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblContent tblContent = db.tblContent.Find(id);
            if (tblContent == null)
            {
                return HttpNotFound();
            }
            return View(tblContent);
        }

        // POST: tblContents/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edite([Bind(Include = "id,title,clevel,description,cid")] tblContent tblContent)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tblContent).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("ContentManagement");
            }
            return View(tblContent);
        }
        // GET: tblContents/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblContent tblContent = db.tblContent.Find(id);
            if (tblContent == null)
            {
                return HttpNotFound();
            }
            return View(tblContent);
        }

        // POST: tblContents/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tblContent tblContent = db.tblContent.Find(id);
            db.tblContent.Remove(tblContent);
            db.SaveChanges();
            return RedirectToAction("ContentManagement");
        }

    }
}

ELearning/ELearning/Views/Editor/ContentManagement.cshtml
<link href="~/Content/DataTables/css/jquery.dataTables.min.css" rel="stylesheet" />

@model IEnumerable<ELearning.Models.tblContent>
@Scripts.Render("~/bundles/bootstrap")
<link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css">
@{
    ViewBag.Title = "គ្រប់គ្រងមាតិការ";
    Layout = "~/Views/Shared/_ContentManagement.cshtml";
}

<h2>គ្រប់គ្រងមាតិការ</h2>
<div>
    <p>
        @Html.ActionLink("New", "Register", "Editor")
    </p>

    <table class="table" id="contentsTable">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.id)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.title)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.clevel)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.description)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.date)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.cid)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.tblCourse.name)
                </th>
                <th class="no-sort"></th>
                <th class="no-sort"></th>
            </tr>
        </thead>

        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.title)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.clevel)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.description)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.date)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.cid)
                    </td>
                    <td>
                        @Html.DisplayFor(model => item.tblCourse.name)
                    </td>
                    <td class="no-sort">
                        @Html.ActionLink("កែប្រែ", "Edite", new { id = item.id }, new { @class = "btn btn-primary" }) 
                        @Html.ActionLink("លុប", "Delete", new { id = item.id }, new { @class = "btn btn-warning" }) 
                        @Html.ActionLink("លម្អិត", "Details", new { id = item.id }, new { @class = "btn btn-danger" })
                    </td>
                  
                </tr>
            }
        </tbody>

    </table>

</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/Scripts/jquery-1.10.2.min.js")
    @Scripts.Render("~/Scripts/DataTables/jquery.dataTables.min.js")

    <script>
        $(document).ready(function () {
            $('#contentsTable').dataTable({
                "columnDefs": [{
                    "targets": 'no-sort',
                    "orderable": false,
                }]
            });
        });
    </script>
}

ELearning/ELearning/Views/Editor/Dashboard.cshtml
@{
    ViewBag.Title = "Dashboard";
}

<h2>Dashboard</h2>

ELearning/ELearning/Views/Editor/Delete.cshtml
@model ELearning.Models.tblContent

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_ContentManagement.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>

    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.clevel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.clevel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cid)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cid)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            @Html.ActionLink("Back to List", "ContentManagement", "", new { @class = "btn btn-primary" })
        </div>
    }
</div>

ELearning/ELearning/Views/Editor/Details.cshtml
@model ELearning.Models.tblContent

@{
    ViewBag.Title = "លំអិត";
    Layout = "~/Views/Shared/_ContentManagement.cshtml";
}

<h2>លំអិត អំពី មេរៀន</h2>

<div>
   
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.clevel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.clevel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cid)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cid)
        </dd>


    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edite", new { id = Model.id }, new { @class = "btn btn-danger" }) |
    @Html.ActionLink("Back to List", "ContentManagement", "", new { @class = "btn btn-primary" })
</p>

ELearning/ELearning/Views/Editor/Edite.cshtml
@model ELearning.Models.tblContent

@{
    ViewBag.Title = "Edit";
     Layout = "~/Views/Shared/_ContentManagement.cshtml";
}
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
       
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.clevel, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.clevel, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.clevel, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.cid, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.cid, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cid, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "ContentManagement", "", new { @class = "btn btn-primary" })
</div>

ELearning/ELearning/Views/Editor/NewContent.cshtml
@model ELearning.Models.tblContent

@{
    ViewBag.Title = "បញ្ចូលមេរៀនថ្មី";
    Layout = "~/Views/Shared/_ContentManagement.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
      
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.clevel, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.clevel, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.clevel, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.cid, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.cid, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cid, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "ContentManagements", "", new { @class = "btn btn-primary" })
</div>