ELearning/ELearning/Controllers/UserAccountController.cs
using ELearning.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;
using System.Net;
using System.Web.Mvc;
using System.Threading.Tasks;
using Microsoft.AspNet.Identity.Owin;

namespace ELearning.Controllers
{
    public class UserAccountController : Controller
    {
        private tblUsersContext db = new tblUsersContext();

        //Get UserAccount/Register
        public ActionResult Register()
        {
            return View();
        }

        //Post UserAccount/Register
        [HttpPost]
        [ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include = "id,name,email,password,logInFreq")] tblUser tblUser)
        public ActionResult Register(tblUser regUser)
        {
            if (ModelState.IsValid)
            {
                db.tblUser.Add(regUser);
                tblStudent tmp = new tblStudent();
                tmp.userId = regUser.id;
                db.tblStudents.Add(tmp);
                db.SaveChanges();
                return RedirectToAction("Index", "Home");
            }
            return View(regUser);
        }

        //Get UserAccount/Login
        public ActionResult Login()
        {
            return View();
        }

        //POST UserAccount/Login
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult Login(loginUser user)
        {
            if (ModelState.IsValid)
            {
                List<tblUser> allUsers = db.tblUser.ToList();
                foreach(tblUser u in allUsers)
                {
                    if(u.email == user.email && u.password == user.password)
                    {
                        if (u.type == "STUDENT")
                        {
                            return RedirectToAction("Index", "Home");
                        }
                        else if (u.type == "ADMIN")
                        {
                            return RedirectToAction("UserManagement", "Admin");
                        }
                        else if (u.type == "EDITOR")
                        {
                            return RedirectToAction("ContentManagement", "Editor");
                        }
                    }
                }
            }
            return View(user);
        }
    }

    
}

ELearning/ELearning/Views/UserAccount/Login.cshtml
@model ELearning.Models.loginUser
@{
    ViewBag.Title = "Log in";
}

<h2>@ViewBag.Title.</h2>
<div class="row">
    <div class="col-md-8">
        <section id="loginForm">
            @using (Html.BeginForm("Login", "UserAccount", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
                @Html.AntiForgeryToken()
                <h4>Use a local account to log in.</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.email, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(model => model.email, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.password, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.PasswordFor(model => model.password, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
                    </div>
                </div>
                @*<div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <div class="checkbox">
                            @Html.CheckBoxFor(m => m.RememberMe)
                            @Html.LabelFor(m => m.RememberMe)
                        </div>
                    </div>
                </div>*@
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Log in" class="btn btn-default" />
                    </div>
                </div>
                <p>
                    @Html.ActionLink("Register as a new user", "Register")
                </p>
                @* Enable this once you have account confirmation enabled for password reset functionality
                    <p>
                        @Html.ActionLink("Forgot your password?", "ForgotPassword")
                    </p>*@
            }
        </section>
    </div>
    @*<div class="col-md-4">
        <section id="socialLoginForm">
            @Html.Partial("_ExternalLoginsListPartial", new ExternalLoginListViewModel { ReturnUrl = ViewBag.ReturnUrl })
        </section>
    </div>*@
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ELearning/ELearning/Views/UserAccount/Register.cshtml
@model ELearning.Models.tblUser

@{
    ViewBag.Title = "Register";
}

<h2>@ViewBag.Title.</h2>


@using (Html.BeginForm("Register", "UserAccount", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Create a new account.</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @*@Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })*@
            @Html.LabelFor(model => model.name, new { @class = "col-md-2 control-label" })
       
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.name, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @*@Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })*@
            @Html.LabelFor(model => model.email, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.email, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @*@Html.LabelFor(model => model.password, htmlAttributes: new { @class = "control-label col-md-2" })*@
            @Html.LabelFor(model => model.password, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.PasswordFor(model => model.password, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @*@Html.LabelFor(model => model.password, htmlAttributes: new { @class = "control-label col-md-2" })*@
            @Html.LabelFor(model => model.confirmpassword, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.PasswordFor(model => model.confirmpassword, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.confirmpassword, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.logInFreq, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.logInFreq, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.logInFreq, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Register" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}